ALTER TABLE IA_BIOSOURCE ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_BIOSOURCE_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);
ALTER TABLE IA_COMPONENT ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_COMPONENT_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);
ALTER TABLE IA_CONTROLLEDVOCAB ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_CONTROLLEDVOCAB_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);
ALTER TABLE IA_EXPERIMENT ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_EXPERIMENT_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);
ALTER TABLE IA_FEATURE ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_FEATURE_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);
ALTER TABLE IA_INSTITUTION ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_INSTITUTION_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);
ALTER TABLE IA_INTERACTOR ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_INTERACTOR_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);
ALTER TABLE IA_PUBLICATION ALTER COLUMN shortlabel TYPE character varying(256);
--ALTER TABLE IA_PUBLICATION_AUDIT ALTER COLUMN shortlabel TYPE character varying(256);


-- ALTER TABLE IA_BIOSOURCESTATISTICS ALTER COLUMN shortlabel TYPE character varying(256);

