ALTER TABLE IA_BIOSOURCE ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_BIOSOURCE_AUDIT ALTER COLUMN fullname TYPE character varying(1000);
ALTER TABLE IA_COMPONENT ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_COMPONENT_AUDIT ALTER COLUMN fullname TYPE character varying(1000);
ALTER TABLE IA_CONTROLLEDVOCAB ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_CONTROLLEDVOCAB_AUDIT ALTER COLUMN fullname TYPE character varying(1000);
ALTER TABLE IA_EXPERIMENT ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_EXPERIMENT_AUDIT ALTER COLUMN fullname TYPE character varying(1000);
ALTER TABLE IA_FEATURE ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_FEATURE_AUDIT ALTER COLUMN fullname TYPE character varying(1000);
ALTER TABLE IA_INSTITUTION ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_INSTITUTION_AUDIT ALTER COLUMN fullname TYPE character varying(1000);
ALTER TABLE IA_INTERACTOR ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_INTERACTOR_AUDIT ALTER COLUMN fullname TYPE character varying(1000);
ALTER TABLE IA_PUBLICATION ALTER COLUMN fullname TYPE character varying(1000);
--ALTER TABLE IA_PUBLICATION_AUDIT ALTER COLUMN fullname TYPE character varying(1000);

-- ALTER TABLE IA_DETECTIONMETHODSSTATISTICS ALTER COLUMN fullname TYPE character varying(1000);

