/**
 * Generated by Agitar build: Agitator Version 1.0.4.000276 (Build date: Mar 27, 2007) [1.0.4.000276]
 * JDK Version: 1.5.0_09
 *
 * Generated on 04-Apr-2007 08:23:24
 * Time to generate: 00:07.639 seconds
 *
 */

package agitar.uk.ac.ebi.intact.modelt;

import uk.ac.ebi.intact.model.*;

import com.agitar.lib.junit.AgitarTestCase;
import uk.ac.ebi.intact.model.util.AnnotatedObjectUtils;

public class CvComponentRoleAgitarTest extends AgitarTestCase {

    static Class TARGET_CLASS = CvComponentRole.class;

    public void testConstructor() throws Throwable {
        Institution owner = new Institution( "testCvComponentRoleShortLabel" );
        CvComponentRole cvComponentRole = new CvComponentRole( owner, "testCvComponentRoleShortLabel" );
        assertEquals( "cvComponentRole.xrefs.size()", 0, cvComponentRole.xrefs.size() );
        assertEquals( "cvComponentRole.getAliases().size()", 0, cvComponentRole.getAliases().size() );
        assertEquals( "cvComponentRole.getEvidences().size()", 0, cvComponentRole.getEvidences().size() );
        assertEquals( "cvComponentRole.shortLabel", "testCvComponentRoleS", cvComponentRole.getShortLabel() );
        assertEquals( "cvComponentRole.annotations.size()", 0, cvComponentRole.annotations.size() );
        assertSame( "cvComponentRole.getOwner()", owner, cvComponentRole.getOwner() );
        assertEquals( "cvComponentRole.references.size()", 0, cvComponentRole.references.size() );
    }

    public void testConstructorThrowsIllegalArgumentException() throws Throwable {
        try {
            new CvComponentRole( new Institution( "testCvComponentRoleShortLabel" ), "" );
            fail( "Expected IllegalArgumentException to be thrown" );
        } catch ( IllegalArgumentException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non empty short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }

    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new CvComponentRole( new Institution( "testCvComponentRoleShortLabel" ), null );
            fail( "Expected NullPointerException to be thrown" );
        } catch ( NullPointerException ex ) {
            assertEquals( "ex.getMessage()", "Must define a non null short label", ex.getMessage() );
            assertThrownBy( AnnotatedObjectUtils.class, ex );
        }
    }
}

