/**
 * Copyright (c) 2002-2006 The European Bioinformatics Institute, and others.
 * All rights reserved. Please see the file LICENSE
 * in the root directory of this distribution.
 */
package uk.ac.ebi.intact.application.statisticView.webapp;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpSessionEvent;
import javax.servlet.http.HttpSessionListener;
import java.io.File;

/**
 * Deletes the temporary charts generated by this session.
 *
 * @author Bruno Aranda (baranda@ebi.ac.uk)
 * @version $Id$
 * @since <pre>02-Aug-2006</pre>
 */
public class ChartDeleterSessionListener implements HttpSessionListener
{

    private static final Log log = LogFactory.getLog(ChartDeleterSessionListener.class);

    public void sessionCreated(HttpSessionEvent httpSessionEvent)
    {
        log.debug("Session created: "+httpSessionEvent.getSession().getId());
    }

    public void sessionDestroyed(HttpSessionEvent httpSessionEvent)
    {
        ServletContext context = httpSessionEvent.getSession().getServletContext();

        String tempDir = "/temp";
        File realTempDir = new File(context.getRealPath(tempDir));

        File[] sessionFilesToDelete = realTempDir.listFiles(new SessionFilenameFilter(httpSessionEvent.getSession()));

        for (File fileToDeFile : sessionFilesToDelete)
        {
            fileToDeFile.delete();
        }

        if (log.isDebugEnabled())
            log.debug("Session destroyed ("+httpSessionEvent.getSession().getId()+"). Files removed: "+sessionFilesToDelete.length);

    }
}
