/*
 * Copyright (c) 2002 The European Bioinformatics Institute, and others.
 * All rights reserved. Please see the file LICENSE
 * in the root directory of this distribution.
 */
package uk.ac.ebi.intact.mocks;

import uk.ac.ebi.intact.model.Annotation;
import uk.ac.ebi.intact.model.CvTopic;

/**
 * TODO comment this
 *
 * @author Catherine Leroy (cleroy@ebi.ac.uk)
 * @version $Id$
 * @since TODO
 */
public class AnnotationMock {

    /**
     * Create an Instutition with :
     *      ac = will have the for EBI- plus a number. Generated by AcGetter.getNextVal()
     *      cvTopic = param cvTopic
     *      description = param description
     *      creator = JEAN
     *      updator = STEEVE
     *      created = 2006, 11th of March
     *      updated = 2007, 22nd of January
     *      owner = InstituctionMock.getMock() (ebi institution)
     * and returns it.
     *
     * @param cvTopic, the cvTopic you want the annotation to have.
     * @param description, the description of the annotation
     *
     * @return an annotation
     */
    public static Annotation getMock(CvTopic cvTopic, String description){
        Annotation annotation = new Annotation(InstitutionMock.getMock(), cvTopic, description);
        annotation.setAc(AcGenerator.getNextVal());
        annotation.setCreated(DateGetter.getCreatedDate());
        annotation.setUpdated(DateGetter.getUpdatedDate());
        annotation.setCreator("JEAN");
        annotation.setUpdator("STEEVE");
        annotation.setOwner(InstitutionMock.getMock());
        return annotation;
    }
}