set serveroutput on

spool 06_enable_triggers.log

ALTER TRIGGER INTACT.TRGAUD_IA_ALIAS ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_ANNOTATION ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_BIOSOURCE ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_BIOSOURCE2ANNOT ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_COMPONENT ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_CONTROLLEDVOCAB ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_CV2CV ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_CVOBJECT2ANNOT ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_EXP2ANNOT ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_EXPERIMENT ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_FEATURE ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_FEATURE2ANNOT ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INSTITUTION ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INT2ANNOT ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INT2EXP ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INTACTNODE ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INTERACTOR ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_PUBMED ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_RANGE ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_SEQUENCE_CHUNK ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_STATISTICS ENABLE; 
ALTER TRIGGER INTACT.TRG_IA_STATISTICS ENABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_XREF ENABLE; 
ALTER TRIGGER INTACT.TRG_XREF_PARENTAC_CHECK ENABLE; 

spool off
