
drop TRIGGER TRG_IA_COMPONENT_XREF_DELETE ON  IA_COMPONENT;
drop TRIGGER TRG_IA_COMPONENT_ALIAS_DELETE ON  IA_COMPONENT;

drop TRIGGER TRG_IA_BIOSOURCE_XREF_DELETE ON  IA_BIOSOURCE;
drop TRIGGER TRG_IA_BIOSOURCE_ALIAS_DELETE ON  IA_BIOSOURCE;

drop TRIGGER TRG_IA_CVOBJECT_XREF_DELETE ON  IA_CONTROLLEDVOCAB;
drop TRIGGER TRG_IA_CVOBJECT_ALIAS_DELETE ON  IA_CONTROLLEDVOCAB;

drop TRIGGER TRG_IA_EXPERIMENT_XREF_DELETE ON  IA_EXPERIMENT; 
drop TRIGGER TRG_IA_EXPERIMENT_ALIAS_DELETE ON  IA_EXPERIMENT; 

drop TRIGGER TRG_IA_FEATURE_XREF_DELETE ON  IA_FEATURE;
drop TRIGGER TRG_IA_FEATURE_ALIAS_DELETE ON  IA_FEATURE;

drop TRIGGER TRG_IA_PUB_XREF_DELETE ON  IA_PUBLICATION;
drop TRIGGER TRG_IA_PUB_ALIAS_DELETE ON  IA_PUBLICATION;

drop TRIGGER TRG_IA_INTERACTOR_XREF_DELETE ON  IA_INTERACTOR;
drop TRIGGER TRG_IA_INTERACTOR_ALIAS_DELETE ON  IA_INTERACTOR;

drop TRIGGER TRG_IA_COMPONENT_XREF_DELETE ON  IA_COMPONENT;
drop TRIGGER TRG_IA_COMPONENT_ALIAS_DELETE ON  IA_COMPONENT;
