ALTER TABLE IA_BIOSOURCE MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_BIOSOURCE_AUDIT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_COMPONENT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_COMPONENT_AUDIT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_CONTROLLEDVOCAB MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_CONTROLLEDVOCAB_AUDIT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_EXPERIMENT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_EXPERIMENT_AUDIT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_FEATURE MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_FEATURE_AUDIT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_INSTITUTION MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_INSTITUTION_AUDIT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_INTERACTOR MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_INTERACTOR_AUDIT MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_PUBLICATION MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_PUBLICATION_AUDIT MODIFY (shortlabel varchar2(256));


ALTER TABLE IA_BIOSOURCESTATISTICS MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_DELETED_ACS MODIFY (shortlabel varchar2(256));
ALTER TABLE IA_PAPERSTATUS MODIFY (shortlabel varchar2(256));

