ALTER TABLE IA_BIOSOURCE MODIFY (fullname varchar2(1000));
ALTER TABLE IA_BIOSOURCE_AUDIT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_COMPONENT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_COMPONENT_AUDIT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_CONTROLLEDVOCAB MODIFY (fullname varchar2(1000));
ALTER TABLE IA_CONTROLLEDVOCAB_AUDIT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_EXPERIMENT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_EXPERIMENT_AUDIT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_FEATURE MODIFY (fullname varchar2(1000));
ALTER TABLE IA_FEATURE_AUDIT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_INSTITUTION MODIFY (fullname varchar2(1000));
ALTER TABLE IA_INSTITUTION_AUDIT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_INTERACTOR MODIFY (fullname varchar2(1000));
ALTER TABLE IA_INTERACTOR_AUDIT MODIFY (fullname varchar2(1000));
ALTER TABLE IA_PUBLICATION MODIFY (fullname varchar2(1000));
ALTER TABLE IA_PUBLICATION_AUDIT MODIFY (fullname varchar2(1000));

ALTER TABLE IA_DETECTIONMETHODSSTATISTICS MODIFY (fullname varchar2(1000));

