set serveroutput on

spool 01_disable_triggers.log

select to_char(sysdate,'dd-mon-yyyy hh24:mi:ss')  start_date from dual;

ALTER TRIGGER INTACT.TRGAUD_IA_ALIAS DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_ANNOTATION DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_BIOSOURCE DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_BIOSOURCE2ANNOT DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_COMPONENT DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_CONTROLLEDVOCAB DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_CV2CV DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_CVOBJECT2ANNOT DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_EXP2ANNOT DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_EXPERIMENT DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_FEATURE DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_FEATURE2ANNOT DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INSTITUTION DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INT2ANNOT DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INT2EXP DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INTACTNODE DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_INTERACTOR DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_PUBMED DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_RANGE DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_SEQUENCE_CHUNK DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_STATISTICS DISABLE; 
ALTER TRIGGER INTACT.TRG_IA_STATISTICS DISABLE; 
ALTER TRIGGER INTACT.TRGAUD_IA_XREF DISABLE; 
ALTER TRIGGER INTACT.TRG_XREF_PARENTAC_CHECK DISABLE; 

spool off