--
-- Adding created_user on all main tables.
--

ALTER TABLE IA_ALIAS ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_ANNOTATION ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_BIOSOURCE ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_BIOSOURCE2ANNOT ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_COMPONENT ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_CONTROLLEDVOCAB ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_CV2CV ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_CVOBJECT2ANNOT ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_EXP2ANNOT ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_EXPERIMENT ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_FEATURE ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_FEATURE2ANNOT ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_INSTITUTION ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_INT2ANNOT ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_INT2EXP ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_INTACTNODE ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_INTERACTOR ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_RANGE ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_SEQUENCE_CHUNK ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;
ALTER TABLE IA_XREF ADD COLUMN created_user character varying(30) DEFAULT USER NOT NULL;

